name: install_and_test
on: [push]
jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
        python-version: '3.6'
      - run: pip install .
      - run: pytest